export const videoJson = {
  "kind": "youtube#searchListResponse",
  "etag": "JR6HwveVkd6wVgpE9NxDi8bNDvY",
  "nextPageToken": "CBUQAA",
  "regionCode": "US",
  "pageInfo": {
      "totalResults": 1000000,
      "resultsPerPage": 21
  },
  "items": [
      {
          "kind": "youtube#searchResult",
          "etag": "WLvQ1v_WLP2BrkunPGQVa-k5PmE",
          "id": {
              "kind": "youtube#video",
              "videoId": "z9Ug-3qhrwY"
          },
          "snippet": {
              "publishedAt": "2020-12-13T19:00:19Z",
              "channelId": "UCx-KWLTKlB83hDI6UKECtJQ",
              "title": "Studio Ghibli Nature Loop | Studio Ghibli | Max",
              "description": "Relax with these peaceful visuals from Studio Ghibli. #StudioGhibli Stream your favorite Studio Ghibli films on HBO Max: ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/z9Ug-3qhrwY/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/z9Ug-3qhrwY/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/z9Ug-3qhrwY/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "HBO Max",
              "liveBroadcastContent": "none",
              "publishTime": "2020-12-13T19:00:19Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "1sCDyvvzcCZkfHdmfDYdI8GZe2o",
          "id": {
              "kind": "youtube#video",
              "videoId": "apP07zXC3QM"
          },
          "snippet": {
              "publishedAt": "2021-04-02T20:26:07Z",
              "channelId": "UCd6QvHk4sPkIfJmsZWK24Kw",
              "title": "Stunning Studio Ghibli Soundtracks HD",
              "description": "Stunning Studio Ghibli Soundtracks HD l|̲̅̅○̲̅̅|̲̅̅=̲̅̅|̲̅̅○̲̅̅|l ♫ Tracks & Artists ♫ 00:00 - wandering - jufus ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/apP07zXC3QM/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/apP07zXC3QM/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/apP07zXC3QM/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "★ 眠そうなキウイ ★",
              "liveBroadcastContent": "none",
              "publishTime": "2021-04-02T20:26:07Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "iDuAEccfKZuHauOwV5faENMJeao",
          "id": {
              "kind": "youtube#video",
              "videoId": "IhYs50GJzIA"
          },
          "snippet": {
              "publishedAt": "2023-01-26T20:21:31Z",
              "channelId": "UC_caRqQRVizD_gMcURKPvMw",
              "title": "Greatest Studio Ghibli Soundtracks | relax, study, sleep",
              "description": "Greatest Studio Ghibli Soundtracks with beautiful backgrounds generated by Midjourney. If you enjoyed some of my work - Buy ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/IhYs50GJzIA/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/IhYs50GJzIA/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/IhYs50GJzIA/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "Vagabond",
              "liveBroadcastContent": "none",
              "publishTime": "2023-01-26T20:21:31Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "56ad2LRhhaThPRn1jL5YZGYc8jE",
          "id": {
              "kind": "youtube#video",
              "videoId": "PHklnuOvxfg"
          },
          "snippet": {
              "publishedAt": "2021-01-28T14:01:38Z",
              "channelId": "UCSsBkf3472xCGaca85b_vWg",
              "title": "studio ghibli playlist (relax, sleep, study)🌱",
              "description": "Enjoy UwUr ✨ . ✨No copyright infringement intended.",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/PHklnuOvxfg/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/PHklnuOvxfg/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/PHklnuOvxfg/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "Wow Annie",
              "liveBroadcastContent": "none",
              "publishTime": "2021-01-28T14:01:38Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "OhNdVHM_DFuuZfQbH_hdpESvHyQ",
          "id": {
              "kind": "youtube#video",
              "videoId": "3jWRrafhO7M"
          },
          "snippet": {
              "publishedAt": "2016-05-10T13:59:56Z",
              "channelId": "UCJhjE7wbdYAae1G25m0tHAA",
              "title": "#GhibliJazz #CafeMusic - Relaxing Jazz &amp; Bossa Nova Music - Studio Ghibli Cover",
              "description": "Studio Ghibli's Music Cover!! * The music in this video is actually being played by BGMC. And the approval of the release on ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/3jWRrafhO7M/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/3jWRrafhO7M/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/3jWRrafhO7M/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "Cafe Music BGM channel",
              "liveBroadcastContent": "none",
              "publishTime": "2016-05-10T13:59:56Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "Hu3Q3UCMbMnRAy31cibo--tiOck",
          "id": {
              "kind": "youtube#video",
              "videoId": "8HGjm0Sk8tk"
          },
          "snippet": {
              "publishedAt": "2020-06-18T12:00:03Z",
              "channelId": "UCCj956IF62FbT7Gouszaj9w",
              "title": "Why Studio Ghibli films have that extra magic | Inside Cinema - BBC",
              "description": "Subscribe and to the BBC https://bit.ly/BBCYouTubeSub Watch the BBC first on iPlayer https://bbc.in/iPlayer-Home ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/8HGjm0Sk8tk/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/8HGjm0Sk8tk/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/8HGjm0Sk8tk/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "BBC",
              "liveBroadcastContent": "none",
              "publishTime": "2020-06-18T12:00:03Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "zq1MHtPH6kfceepSbR2idqBELXc",
          "id": {
              "kind": "youtube#video",
              "videoId": "HGl75kurxok"
          },
          "snippet": {
              "publishedAt": "2018-02-26T05:40:03Z",
              "channelId": "UCn_BfXemOYNRIxQpxiXkUKw",
              "title": "Piano Ghibli Collection 1",
              "description": "Listen to this on Spotify: https://open.spotify.com/playlist/3SdLJNrKiqgnulRbxGs65G?si=ef3c20b8dc884b18 Part 2: ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/HGl75kurxok/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/HGl75kurxok/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/HGl75kurxok/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "Vangakuz ヴァンガクズ",
              "liveBroadcastContent": "none",
              "publishTime": "2018-02-26T05:40:03Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "qKqE95oGfdv8E6q3LKDfKBywKoo",
          "id": {
              "kind": "youtube#video",
              "videoId": "G2gabgXzMLE"
          },
          "snippet": {
              "publishedAt": "2021-09-24T17:07:57Z",
              "channelId": "UC5UYMeKfZbFYnLHzoTJB1xA",
              "title": "Every Studio Ghibli Movie Ranked",
              "description": "Head to http://squarespace.com/schaffrillas​​​​​ to save 10% off your first purchase of a website or domain. Thanks to ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/G2gabgXzMLE/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/G2gabgXzMLE/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/G2gabgXzMLE/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "Schaffrillas Productions",
              "liveBroadcastContent": "none",
              "publishTime": "2021-09-24T17:07:57Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "QUMVjoJUEnOBYua0IuKsNzPMY3k",
          "id": {
              "kind": "youtube#video",
              "videoId": "HTlKoYCD96I"
          },
          "snippet": {
              "publishedAt": "2023-01-04T11:00:07Z",
              "channelId": "UC992aW0kfy4lttcg1ESSBWA",
              "title": "4 時間  ジブリメドレーピアノ💖【Relaxing Ghibli】Piano Studio Ghibli Collection 🌹 少なくとも1 回 は 聞くべ き🍀 となりのトトロ、崖の上のポニョ",
              "description": "4 時間 ジブリメドレーピアノ  【Relaxing Ghibli】Piano Studio Ghibli Collection 少なくとも1 回 は 聞くべ き   となりの ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/HTlKoYCD96I/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/HTlKoYCD96I/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/HTlKoYCD96I/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "BGM Ghibli Studio",
              "liveBroadcastContent": "none",
              "publishTime": "2023-01-04T11:00:07Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "hjkagwRUyYNW31Yk1wyZTCXHdLs",
          "id": {
              "kind": "youtube#video",
              "videoId": "0jZNKV5ROBM"
          },
          "snippet": {
              "publishedAt": "2020-05-26T05:37:38Z",
              "channelId": "UCxyzciBLt1Hyw06dlqwAIkw",
              "title": "Joe Hisaishi : Studio Ghibli Experience, Part 1",
              "description": "https://linktr.ee/joehisaishi ▻ https://deccagold.lnk.to/DreamSongs 0:00 - One Summer's Day 4:32 - The Sixth Station 8:23 ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/0jZNKV5ROBM/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/0jZNKV5ROBM/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/0jZNKV5ROBM/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "Joe Hisaishi Official",
              "liveBroadcastContent": "none",
              "publishTime": "2020-05-26T05:37:38Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "agL0WYGl2AUivGC0ryglU5AaaCQ",
          "id": {
              "kind": "youtube#video",
              "videoId": "bHFKkCcUjW0"
          },
          "snippet": {
              "publishedAt": "2023-01-14T00:47:06Z",
              "channelId": "UC_caRqQRVizD_gMcURKPvMw",
              "title": "1 hour of Studio Ghibli | Relaxing Piano Music (relax, study, sleep)",
              "description": "0:00:00 Kiki's Delivery Service - Umi no Mieru Machi 0:04:44 My Neighbor Totoro - Kaze no Toori Michi 0:10:12 Princess ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/bHFKkCcUjW0/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/bHFKkCcUjW0/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/bHFKkCcUjW0/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "Vagabond",
              "liveBroadcastContent": "none",
              "publishTime": "2023-01-14T00:47:06Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "h-dq6TZSjjJAOnAgjWJg7mHBkrM",
          "id": {
              "kind": "youtube#video",
              "videoId": "XKd-qdNNko4"
          },
          "snippet": {
              "publishedAt": "2020-06-15T00:00:13Z",
              "channelId": "UCT2Dh6WXU33MgA0vz-tzfIw",
              "title": "Studio Ghibli   Music Collection Piano and Violin Duo 株式会社スタジオジブリ  Relaxing music song",
              "description": "Studio Ghibli Music Collection Piano and Violin Duo 株式会社スタジオジブリ Relaxing music song https://youtu.be/XKd-qdNNko4 ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/XKd-qdNNko4/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/XKd-qdNNko4/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/XKd-qdNNko4/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "TalesWeaver music",
              "liveBroadcastContent": "none",
              "publishTime": "2020-06-15T00:00:13Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "gMDlWuqhDkVmMHG6Ucvb_AedF-Y",
          "id": {
              "kind": "youtube#video",
              "videoId": "xJWLxxD0Hp8"
          },
          "snippet": {
              "publishedAt": "2016-09-01T22:00:02Z",
              "channelId": "UCaWd5_7JhbQBe4dknZhsHJg",
              "title": "Top 10 Best Studio Ghibli Movies",
              "description": "Top 10 Best Studio Ghibli Movies Subscribe http://goo.gl/Q2kKrD This list countdowns the best movies by legendary Japanese ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/xJWLxxD0Hp8/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/xJWLxxD0Hp8/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/xJWLxxD0Hp8/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "WatchMojo.com",
              "liveBroadcastContent": "none",
              "publishTime": "2016-09-01T22:00:02Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "zPkJe2MXFnSdAK2tSf9rZaMlp9M",
          "id": {
              "kind": "youtube#video",
              "videoId": "oQUA3tQS0To"
          },
          "snippet": {
              "publishedAt": "2021-07-27T10:00:32Z",
              "channelId": "UCVX_4LoUm4mdZBPdpMJkkSQ",
              "title": "Studio Ghibli Summer Night Deep Sleep Piano Medley(No Mid-roll Ads)",
              "description": "Thank you for visiting kno Music Channel. The music is arranged and performed by kno. To deliver you an enjoyment of the full ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/oQUA3tQS0To/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/oQUA3tQS0To/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/oQUA3tQS0To/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "kno Music",
              "liveBroadcastContent": "none",
              "publishTime": "2021-07-27T10:00:32Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "0zkn1eqQezCDizwXkMFIe1BSOXE",
          "id": {
              "kind": "youtube#video",
              "videoId": "uCHuTxVYtsk"
          },
          "snippet": {
              "publishedAt": "2023-03-14T13:30:41Z",
              "channelId": "UC992aW0kfy4lttcg1ESSBWA",
              "title": "【Spring Ghibli Piano 】💛 考えすぎるのをやめる 🌻 4時間  ジブリメドレーピアノ💖 ジブリ音楽はポジティブなエネルギーをもたらします 💎魔女の宅急便, となりのトトロ",
              "description": "【Spring Ghibli Piano 】   考えすぎるのをやめる 4時間 ジブリメドレーピアノ   ジブリ音楽はポジティブなエネルギーを ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/uCHuTxVYtsk/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/uCHuTxVYtsk/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/uCHuTxVYtsk/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "BGM Ghibli Studio",
              "liveBroadcastContent": "none",
              "publishTime": "2023-03-14T13:30:41Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "F5RzDCBt-OlpJuN-5gVSYypu6BQ",
          "id": {
              "kind": "youtube#video",
              "videoId": "Q-Hv5WkRfBI"
          },
          "snippet": {
              "publishedAt": "2021-11-06T19:00:11Z",
              "channelId": "UCxgJZxXviSbPbEMrsO6DpuQ",
              "title": "Rating Every Studio Ghibli Movie from BEST to WORST",
              "description": "From Spirited Away to Howl's moving Castle, we're gonna decide which Studio Ghibli films suck and which ones are GOATed.",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/Q-Hv5WkRfBI/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/Q-Hv5WkRfBI/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/Q-Hv5WkRfBI/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "Joey Bizinger",
              "liveBroadcastContent": "none",
              "publishTime": "2021-11-06T19:00:11Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "K7igYC8ZGUKL6t9hJ1xMFNBOkxM",
          "id": {
              "kind": "youtube#video",
              "videoId": "jLPNkXglCwQ"
          },
          "snippet": {
              "publishedAt": "2022-04-15T16:00:20Z",
              "channelId": "UCzjbia0NqUsSL1_-loJihMg",
              "title": "one of the greatest scenes ever animated",
              "description": "SpiritedAway #HayaoMiyazaki #VideoEssay You can support me at: www.Patreon.com/CinemaStix An analysis of the train scene ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/jLPNkXglCwQ/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/jLPNkXglCwQ/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/jLPNkXglCwQ/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "CinemaStix",
              "liveBroadcastContent": "none",
              "publishTime": "2022-04-15T16:00:20Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "WnY0Mv-3aDeBjaZnhsNNsuYGEKs",
          "id": {
              "kind": "youtube#video",
              "videoId": "ebMQ_4qM_bI"
          },
          "snippet": {
              "publishedAt": "2023-01-08T16:08:10Z",
              "channelId": "UCeJm75fBDYkAamZessjMv_w",
              "title": "Studio Ghibli Playlist (1 Hour of Relaxing Studio Ghibli Piano)",
              "description": "Remember that you are loved ❤️ ✨ Feel free to come and stay a while and listen to some lofi beats to study/relax to ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/ebMQ_4qM_bI/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/ebMQ_4qM_bI/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/ebMQ_4qM_bI/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "Lofi Central",
              "liveBroadcastContent": "none",
              "publishTime": "2023-01-08T16:08:10Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "Fu92t05I3u4tu_O4pSHQIWGbTs8",
          "id": {
              "kind": "youtube#video",
              "videoId": "k2dnUS41NQs"
          },
          "snippet": {
              "publishedAt": "2022-12-09T23:00:06Z",
              "channelId": "UC992aW0kfy4lttcg1ESSBWA",
              "title": "ジブリメドレーピアノ4 時 間 💖【Relaxing Ghibli】 史 上 最 高 のピアノジブリコレクション 🌹  少なくとも1 回 は 聞くべ き 🍀 となりのトトロ、ハウルの動く城",
              "description": "ジブリメドレーピアノ4 時 間 【Relaxing Ghibli】 史 上 最 高 のピアノジブリコレクション 少なくとも1 回 は 聞くべ き, ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/k2dnUS41NQs/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/k2dnUS41NQs/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/k2dnUS41NQs/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "BGM Ghibli Studio",
              "liveBroadcastContent": "none",
              "publishTime": "2022-12-09T23:00:06Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "ug3Zm7FM3mniBr8rTtSUa27xITI",
          "id": {
              "kind": "youtube#video",
              "videoId": "AZals4U6Z_I"
          },
          "snippet": {
              "publishedAt": "2019-06-28T20:13:21Z",
              "channelId": "UCPYOkAZJVfGAQapiqJEg5Mg",
              "title": "chill / relax / study music | studio ghibli lo-fi jazz mix",
              "description": "studio ghibli study / relaxation music please leave a like it really helps me out! instagram: miyukistudies feel free to leave any ...",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/AZals4U6Z_I/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/AZals4U6Z_I/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/AZals4U6Z_I/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "Miyuki Studies",
              "liveBroadcastContent": "none",
              "publishTime": "2019-06-28T20:13:21Z"
          }
      },
      {
          "kind": "youtube#searchResult",
          "etag": "yoaixgfZUIUGJnrYaOVlWk5G_5k",
          "id": {
              "kind": "youtube#video",
              "videoId": "SEzAoQJZOhc"
          },
          "snippet": {
              "publishedAt": "2021-07-07T16:46:25Z",
              "channelId": "UCExJNA8ZMfefFib96Gd-Lpw",
              "title": "4K VIDEO | RELAXING STUDIO GHIBLI COMPLETE PIANO MUSIC COLLECTION | BEAUTIFUL ANIME VIDEO",
              "description": "Je tiens à remercier ceux qui me soutiennent, commentent, like et s'abonnent à ma chaîne, j'espère que vous aimerez ma vidéo.",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/SEzAoQJZOhc/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/SEzAoQJZOhc/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/SEzAoQJZOhc/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "SOUND OF NATURE",
              "liveBroadcastContent": "none",
              "publishTime": "2021-07-07T16:46:25Z"
          }
      }
  ]
}